permalink: date
#markdown: kramdown
markdown: redcarpet
highlighter: pygments

redcarpet:
  extensions:
    - fenced_code_blocks
    - no_intra_emphasis
    - strikethrough
    - autolink
    - tables
#kramdown:
#  input: GFM
#  auto_ids: true
#  auto_id_prefix: 'id-'

# 作者信息
author: 
  name: cherrot
  email: cherrotluo@gmail.com
  link: http://cherrot.com
  github: http://github.com/cherrot

# 站点信息
title: cherrot's daily
description: happy hacking :)
url: http://cherrot.com
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: http://en.gravatar.com/userimage/15965667/81ec86b4ed649c9043cdb705c5afccef.png
#favicon: http://7u2ho6.com1.z0.glb.clouddn.com/site-favicon.ico
favicon: '/favicon.ico'

# google analytics 设置
#ga:
#  id: UA-54767140-1
#  url: yansu.org

# disqus 设置
disqus:
  shortname: cherrot
