# Site settings
title: Cherrot's
description: Happy hacking :)
url: https://cherrot.com
baseurl: "" # the subpath of your site, e.g. /blog/
rss_url: /feed

# Author
author: Cherrot Luo
email: cherrotluo@gmail.com
github: cherrot
twitter: cherrot
# weibo: cherrot
# instagram: cherrot
# linkedin: cherrot

# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
filter: 'category'
recent_num: 50

# avatar
avatar: https://en.gravatar.com/userimage/15965667/81ec86b4ed649c9043cdb705c5afccef.png
favicon: '/favicon.ico'

# Format
permalink: date
# permalink: /:year/:month/:day/:title
markdown: kramdown
#markdown: redcarpet
highlighter: rouge
kramdown:
  input: GFM
mathjax: disabled
sass:
  style: compressed

# google analytics
ga:
  id: "UA-16507835-6"
  url: "auto"

# disqus
disqus:
  shortname: cherrot

# set timezone to avoid jekyll skpping my post for its 'future date'
#timezone: '+0800'
future: true

# Jekyll Plugin
# https://help.github.com/articles/adding-jekyll-plugins-to-a-github-pages-site/
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
